#!/usr/bin/env python3
"""Generate calculator-native UI assets from the approved CasioGPT artwork."""

from pathlib import Path
from PIL import Image, ImageDraw, ImageFont


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "assets/CasioGPT/source/casiogpt-splash-generated.png"
SPLASH_PNG = ROOT / "assets/CasioGPT/casiogpt-splash-384.png"
SPLASH_HEADER = ROOT / "apps/CasioGPT/src/splash.h"
AVATAR_HEADER = ROOT / "apps/CasioGPT/src/avatar.h"
ROOT_CERT = Path("/etc/ssl/certs/GTS_Root_R1.pem")
CERT_HEADER = ROOT / "firmware/casioesp_wifi/gts_root_r1.h"


def font(size: int):
    paths = (
        "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
        "/usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf",
    )
    for path in paths:
        if Path(path).exists():
            return ImageFont.truetype(path, size)
    return ImageFont.load_default()


def rgb565(pixel):
    r, g, b = pixel[:3]
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)


def write_u16_header(path: Path, name: str, image: Image.Image):
    raw = image.convert("RGB").tobytes()
    values = [rgb565(raw[start:start + 3]) for start in range(0, len(raw), 3)]
    lines = [
        "/* Generated by tools/generate-assets.py; do not edit. */",
        f"#define {name.upper()}_W {image.width}",
        f"#define {name.upper()}_H {image.height}",
        f"static const unsigned short {name}_pixels[] = {{",
    ]
    for start in range(0, len(values), 16):
        lines.append("    " + ",".join(f"0x{value:04X}" for value in values[start:start + 16]) + ",")
    lines.append("};")
    path.write_text("\n".join(lines) + "\n", encoding="ascii")


def write_alpha_header(path: Path, name: str, image: Image.Image):
    values = list(image.convert("L").tobytes())
    lines = [
        "/* Generated by tools/generate-assets.py; do not edit. */",
        f"#define {name.upper()}_W {image.width}",
        f"#define {name.upper()}_H {image.height}",
        f"static const unsigned char {name}_alpha[] = {{",
    ]
    for start in range(0, len(values), 24):
        lines.append("    " + ",".join(str(value) for value in values[start:start + 24]) + ",")
    lines.append("};")
    path.write_text("\n".join(lines) + "\n", encoding="ascii")


def make_menu_icon(logo_alpha: Image.Image, selected: bool):
    bg = (17, 24, 39) if not selected else (10, 107, 255)
    border = (69, 78, 94) if not selected else (0, 42, 112)
    image = Image.new("RGB", (92, 64), bg)
    draw = ImageDraw.Draw(image)
    draw.rounded_rectangle((5, 4, 86, 59), radius=9, outline=border, width=3)
    mark = logo_alpha.resize((44, 44), Image.Resampling.LANCZOS)
    white = Image.new("RGB", mark.size, (255, 255, 255))
    image.paste(white, (24, 10), mark)
    return image


def main():
    source = Image.open(SOURCE).convert("RGB")
    splash = source.resize((384, 216), Image.Resampling.LANCZOS)
    draw = ImageDraw.Draw(splash)
    site = "samilososami.com"
    site_font = font(12)
    box = draw.textbbox((0, 0), site, font=site_font)
    draw.text((378 - (box[2] - box[0]), 211 - (box[3] - box[1])), site, fill=(20, 20, 20), font=site_font)
    splash.save(SPLASH_PNG, optimize=True)
    write_u16_header(SPLASH_HEADER, "casiogpt_splash", splash)

    # The generated source is 1672x941. This square contains only the knot,
    # without the wordmark, and is thresholded into a smooth alpha mask.
    logo = source.crop((500, 45, 1165, 690)).resize((96, 96), Image.Resampling.LANCZOS)
    gray = logo.convert("L")
    alpha = gray.point(lambda value: 255 - value)
    alpha = alpha.resize((22, 22), Image.Resampling.LANCZOS)
    write_alpha_header(AVATAR_HEADER, "casiogpt_avatar", alpha)

    make_menu_icon(alpha, True).save(ROOT / "apps/CasioGPT/selected.bmp")
    make_menu_icon(alpha, False).save(ROOT / "apps/CasioGPT/unselected.bmp")

    cert = ROOT_CERT.read_text(encoding="ascii").strip()
    CERT_HEADER.write_text(
        "/* Mozilla GTS Root R1, copied from the host CA bundle. */\n"
        "static const char GTS_ROOT_R1[] PROGMEM = R\"CERT(\n"
        + cert
        + "\n)CERT\";\n",
        encoding="ascii",
    )


if __name__ == "__main__":
    main()
