#!/usr/bin/env python3
"""Generate antialiased title coverage; no framebuffer upscaling on the CG50."""
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont
root = Path(__file__).resolve().parents[1]
font = ImageFont.truetype('/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf', 27)
box = font.getbbox('CasioWIFI')
im = Image.new('L', (box[2]-box[0]+2, box[3]-box[1]+2))
ImageDraw.Draw(im).text((1-box[0], 1-box[1]), 'CasioWIFI', font=font, fill=255)
values = list(im.getdata())
text = '/* Generated by tools/render-ui-assets.py */\n'
text += f'#define BRAND_W {im.width}\n#define BRAND_H {im.height}\n'
text += 'static const unsigned char brand_alpha[] = {\n'
text += '\n'.join(','.join(map(str, values[i:i+24]))+',' for i in range(0,len(values),24))
text += '\n};\n'
(root/'apps/CasioWIFI/src/brand.h').write_text(text)

font = ImageFont.truetype('/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf', 11)
text = '/* Generated antialiased UI font, 11px at native resolution. */\n'
text += '#define UI_AA_W 12\n#define UI_AA_H 14\nstatic const unsigned char ui_aa[95][169] = {\n'
for code in range(32,127):
    glyph = Image.new('L',(12,14))
    ImageDraw.Draw(glyph).text((0,0),chr(code),font=font,fill=255)
    width = min(12,max(2,round(font.getlength(chr(code)))))
    text += '{'+','.join(map(str,[width]+list(glyph.getdata())))+'},\n'
text += '};\n'
(root/'apps/CasioWIFI/src/ui_aa.h').write_text(text)
